apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: topic2
  labels:
    cluster: {{ .Values.cluster }}
spec:
  partitions: 1
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 10737418
